version: "3.1"

services:
  mysql_dev:
    image: mysql
    environment:
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
      - MYSQL_DATABASE=pizza_dev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_dev_volume:/var/lib/mysql
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 512M

  backend_dev:
    build: ./
    container_name: pizza_backend
    environment:
      - DB_HOST=mysql_dev
      - DB_NAME=pizza_dev
      - DB_USER=devuser
      - DB_PASS=devpass
    ports:
      - "3001:3001"
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 256M

  frontend_dev:
    build:
      context: ./
      args:
        - REACT_APP_API_URL=http://3.22.200.226
    container_name: pizza_frontend
    environment:
      - IS_FRONTEND=true
      - DB_HOST=mysql_dev
      - DB_NAME=pizza_dev
      - DB_USER=devuser
      - DB_PASS=devpass
    ports:
      - "3000:3000"
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 256M

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - frontend_dev
      - backend_dev

volumes:
  mysql_dev_volume:
